extends RefCounted
## Shared palette of the yard prototype: one look for yard, players, items and UI.

const SKY := Color("1b2836")
const AMBIENT := Color("bed7d8")
const SUN := Color("ffd6a2")
const GRASS_A := Color("3f7a52")
const GRASS_B := Color("47905c")
const CHALK := Color("e6efdd")
const POSTS := Color("f2efe6")
const NET := Color("9fb8ae")
const WOOD := Color("6e5136")
const BENCH := Color("b48056")
const BUILDING := Color("3a4f57")
const WINDOWS := Color("cfab71")
const FENCE := Color("526965")
const STRIKER_JERSEY := Color("c65b40")
const KEEPER_JERSEY := Color("4f93a8")
const SHORTS := Color("314858")
const SKIN := Color("e4bd91")
const HOST_ITEM := Color("dfaa61")
const GUEST_ITEM := Color("69b5c5")
const AIM := Color("a2e1c1")
const TRAIL := Color("e4b26e")
const MARKER := Color("769682")
